<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Preparacion de la serie | Bookdown Analisis Series Tiempo</title>
  <meta name="description" content="En este bookdown se empezaran a ir desarrollando las distintas actividades del curso de Analisis Series de tiempo para el correcto estudio de estas tomando en cuenta sus distintas caracteristicas" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Preparacion de la serie | Bookdown Analisis Series Tiempo" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="En este bookdown se empezaran a ir desarrollando las distintas actividades del curso de Analisis Series de tiempo para el correcto estudio de estas tomando en cuenta sus distintas caracteristicas" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Preparacion de la serie | Bookdown Analisis Series Tiempo" />
  
  <meta name="twitter:description" content="En este bookdown se empezaran a ir desarrollando las distintas actividades del curso de Analisis Series de tiempo para el correcto estudio de estas tomando en cuenta sus distintas caracteristicas" />
  

<meta name="author" content="Santiago Restrepo Aguilar" />


<meta name="date" content="2024-11-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="modelo-de-regresion-lineal.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Contexto inicial</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Preparacion de la serie</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#evaluacion-de-nuestra-serie-de-tiempo-inicial"><i class="fa fa-check"></i><b>2.1</b> Evaluacion de nuestra serie de tiempo inicial</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#una-nueva-serie-de-tiempo"><i class="fa fa-check"></i><b>2.2</b> Una Nueva Serie de tiempo</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="modelo-de-regresion-lineal.html"><a href="modelo-de-regresion-lineal.html"><i class="fa fa-check"></i><b>3</b> Modelo de regresion Lineal</a></li>
<li class="chapter" data-level="4" data-path="transformacion-a-serie-estacionaria.html"><a href="transformacion-a-serie-estacionaria.html"><i class="fa fa-check"></i><b>4</b> Transformacion a serie estacionaria</a></li>
<li class="chapter" data-level="5" data-path="modelo-holt-winters.html"><a href="modelo-holt-winters.html"><i class="fa fa-check"></i><b>5</b> Modelo Holt-Winters</a></li>
<li class="chapter" data-level="6" data-path="modelo-arima.html"><a href="modelo-arima.html"><i class="fa fa-check"></i><b>6</b> Modelo Arima</a></li>
<li class="chapter" data-level="7" data-path="modelo-facebooks-prophet.html"><a href="modelo-facebooks-prophet.html"><i class="fa fa-check"></i><b>7</b> Modelo Facebook’s Prophet</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bookdown Analisis Series Tiempo</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Preparacion de la serie<a href="intro.html#intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Comenzamos entonces haciendo estudios primarios a nuestros datos. Comenzamos cargando algunas librerias de interes</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="intro.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb1-2"><a href="intro.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(tseries)</span>
<span id="cb1-3"><a href="intro.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="intro.html#cb1-4" tabindex="-1"></a><span class="fu">library</span>(changepoint)</span>
<span id="cb1-5"><a href="intro.html#cb1-5" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-6"><a href="intro.html#cb1-6" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="intro.html#cb1-7" tabindex="-1"></a><span class="fu">library</span>(zoo)</span>
<span id="cb1-8"><a href="intro.html#cb1-8" tabindex="-1"></a><span class="fu">library</span>(dygraphs)</span>
<span id="cb1-9"><a href="intro.html#cb1-9" tabindex="-1"></a><span class="fu">library</span>(seasonal)</span>
<span id="cb1-10"><a href="intro.html#cb1-10" tabindex="-1"></a><span class="fu">library</span>(TSA)</span>
<span id="cb1-11"><a href="intro.html#cb1-11" tabindex="-1"></a><span class="fu">library</span>(prophet)</span></code></pre></div>
<pre><code>## Warning: package &#39;prophet&#39; was built under R version 4.4.2</code></pre>
<div id="evaluacion-de-nuestra-serie-de-tiempo-inicial" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Evaluacion de nuestra serie de tiempo inicial<a href="intro.html#evaluacion-de-nuestra-serie-de-tiempo-inicial" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Empezaremos definiendo una serie de tiempo en los datos relacionados al ‘GPD per capita’:</p>
<ul>
<li><p>Los datos son tomados de forma anual entonces nuestra serie de tiempo mantendra el mismo formato de tiempo (En años).</p></li>
<li><p>la fecha de interes sera a partir de 1990 (ligado a la crisis de exportaciones) y la fecha de finalizacion sera en 2022 (ligado al fin de la pandemia y al inicio del conflicto rusia-ucrania)</p></li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="intro.html#cb3-1" tabindex="-1"></a>gpd_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;gpd_per_capita.csv&quot;</span>)</span>
<span id="cb3-2"><a href="intro.html#cb3-2" tabindex="-1"></a>gdp_colombia <span class="ot">&lt;-</span> gpd_data <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="intro.html#cb3-3" tabindex="-1"></a>  <span class="fu">filter</span>(Entity <span class="sc">==</span> <span class="st">&quot;Colombia&quot;</span>)</span>
<span id="cb3-4"><a href="intro.html#cb3-4" tabindex="-1"></a>Datos <span class="ot">&lt;-</span> gdp_colombia<span class="sc">$</span>GDP.per.capita..PPP..constant.<span class="fl">2017.</span>international...</span>
<span id="cb3-5"><a href="intro.html#cb3-5" tabindex="-1"></a>ST_COL <span class="ot">&lt;-</span> <span class="fu">ts</span>(Datos, <span class="at">frequency=</span><span class="dv">1</span>, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">1990</span>))</span></code></pre></div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="intro.html#cb4-1" tabindex="-1"></a>(ST_COL)</span></code></pre></div>
<pre><code>## Time Series:
## Start = 1990 
## End = 2022 
## Frequency = 1 
##  [1]  8434.959  8430.223  8598.992  8885.187  9220.502  9518.260  9538.272
##  [8]  9691.028  9578.656  9023.621  9138.319  9146.405  9232.627  9453.328
## [15]  9816.277 10150.708 10692.728 11272.578 11507.525 11507.717 11890.203
## [22] 12578.016 12934.966 13465.075 13938.231 14215.688 14358.168 14334.915
## [29] 14426.435 14616.135 13358.298 14661.213 15616.752</code></pre>
<p>Veamos datos generales</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="intro.html#cb6-1" tabindex="-1"></a><span class="fu">summary</span>(ST_COL)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8430    9233   10693   11310   13465   15617</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="intro.html#cb8-1" tabindex="-1"></a><span class="fu">mean</span>(ST_COL)</span></code></pre></div>
<pre><code>## [1] 11310.06</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="intro.html#cb10-1" tabindex="-1"></a><span class="fu">var</span>(ST_COL)</span></code></pre></div>
<pre><code>## [1] 5318247</code></pre>
<p>Se observan 3 cosas:</p>
<ul>
<li><p>El Maximo ‘GDP per capita’ registrado en la historia del pais (hasta 2022) es de 12617, contrario al minimo reghistrado que es de 8430</p></li>
<li><p>El promedio registrado a travez de los años es de aproximadamente 11310
luego observamos la serie de tiempo en forma de grafica</p></li>
<li><p>La varianza es notablemente alta e indica que los datos estan muy dispersos alrededor del promedio, lo que indica que este ultimo no es un indicador recomendado para determinar el comportamiento que tendra el pais respecto a esta metrica en los años que vienen</p></li>
</ul>
<p>Viendo el grafico de la serie de tiempo</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="intro.html#cb12-1" tabindex="-1"></a><span class="fu">plot</span>(ST_COL, <span class="at">main=</span><span class="st">&quot; &quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Valor&quot;</span>,<span class="at">col=</span><span class="st">&quot;deepskyblue&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Años&quot;</span>)</span>
<span id="cb12-2"><a href="intro.html#cb12-2" tabindex="-1"></a><span class="fu">title</span>(<span class="at">main=</span><span class="st">&quot;Valores anuales del gdp per capita del pais colombiano&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>En el grafico podemos evidenciar una creciente tendencia de los valores a partir de 1990, eso es obvio dado que a partir de estos años posteriores se han ido incrementando mas el proceso de globalizacion con el tema de exportaciones y aperturas del comercio que se afianzaron con los años. Sin embargo podemos evidenciar tambien en la grafica dos desaceleraciones notables:</p>
<ul>
<li><p>Entre 1998 y 2000, la explicacion historica a esta desaceleracion fuerte se da a que durante estas epocas el pais estuvo azotado por multiples conflictos entre el ejercito, las autodefensas y las FARC, destinando la mayor parte de los recursos del estado al ejercito y a la asistencia de las multiples victimas civiles sufridas</p></li>
<li><p>Entre 2019 y 2020, la explicacion historica a esta aun mas fuerte desaceleracion se da a un fenomeno mundial, claramente la pandemia por covid-19 que puso en jaque la economia global de la cual colombia tuvo que cerrar multiples importaciones y exportaciones como medidas preventivas</p></li>
</ul>
<p>Ahora, no es suficiente solo concretar nuestra base de datos en una serie de tiempo. Es vital determinar si nuestros datos presentan estacionalidad o no (concretamente, si nuestra base de datos presenta ciertos patrones recurrentes que se repiten en ciertos intervalo de tiempo).</p>
<p>Para esta primera deteccion usaremos una grafica de rezagos</p>
<p>Para esta tarea usaremos la funcion lag.plot y nos apegaremos a hacerlo en 9 rezagos</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="intro.html#cb13-1" tabindex="-1"></a><span class="fu">lag.plot</span>(ST_COL, <span class="dv">9</span>, <span class="at">do.lines =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Viendo cada rezago de manera cuidadosa, podemos observar un comportamiento identificable en el grafico 1, mas especificamente una alineacion diagonal. Esto nos indica que existe la posibilidad de que nuestra serie de tiempo presente una tendencia, sin embargo, este comportamiento no se vuelve a repetir en los otros rezagos y no se identifica mas comportamientos identificables en las otras graficas, por ende podemos decir que nuestros datos no presentan un patron estacional concreto o que la estacionalidad es muy debil</p>
<p>Que significa esto? que hay que eliminar los componentes estacionales debiles de nuestro modelo, pues estos no presentan algun aporte ni ninguna diferencia significativa frente a datos que no lo tienen.</p>
<p>El siguiente paso seria filtrar el comportamiento estacional de nuestra serie de tiempo. Sin embargo hay un problema y es que nuestra serie de tiempo es anual, esto dificultaria mas la tarea ya que la estacionalidad usualmente se presenta en intervalos mensuales o a lo mucho trimestrales, lo que complica mas el proceso de depuracion, sin embargo hay una solucion a esto y es crear una nueva serie de tiempo de frecuencia trimestral usando datos aproximados a partir de los originales.</p>
<p>Investigando un poco mas, el paquete ‘zoo’ nos permite crear datos adicionales usando tecnicas de interpolacion. Esto es muy util ya que estos datos sirven como aproximaciones que pueden añadirse en nuestra serie de tiempo original, para poder convertirla luego en una serie de tiempo ya sea trimestral o mensual que es lo que buscamos.</p>
</div>
<div id="una-nueva-serie-de-tiempo" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Una Nueva Serie de tiempo<a href="intro.html#una-nueva-serie-de-tiempo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El primer paso es convertir nuestra serie en un objeto de tipo ‘zoo’, esto para volverla una serie de tiempo flexible y poder aplicarle las tecnicas de interpolacion</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="intro.html#cb14-1" tabindex="-1"></a>años <span class="ot">&lt;-</span> <span class="dv">1990</span><span class="sc">:</span><span class="dv">2022</span></span>
<span id="cb14-2"><a href="intro.html#cb14-2" tabindex="-1"></a>COL_zoo <span class="ot">&lt;-</span> <span class="fu">zoo</span>(ST_COL, <span class="at">order.by =</span> años)</span></code></pre></div>
<p>A continuacion utilizaremos interpolacion lineal para crear datos aproximados y definir la serie equivalente en tiempos trimestrales. Hay que tener en cuenta que usamos interpolacion lineal porque es el metodo de interpolacion mas sencillo que ofrece el paquete Zoo y porque concuerda mejor con la aproximacion diagonal que presento el primer retazo en la serie de graficos anteriores, luego definimos la nueva serie de tiempo de frecuencia trimestral debido a que es el periodo de tiempo que mas se acerca a los datos anuales, tampoco buscamos tentar mucho el nivel de aproximacion que podamos obtener al crear muchisimos datos entre cada dato original.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="intro.html#cb15-1" tabindex="-1"></a><span class="co"># Crear una secuencia de fechas trimestrales(a partir de las funcion as.Date mostrada en los contenidps)</span></span>
<span id="cb15-2"><a href="intro.html#cb15-2" tabindex="-1"></a>start_year <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;1990-01-01&quot;</span>)</span>
<span id="cb15-3"><a href="intro.html#cb15-3" tabindex="-1"></a>end_year <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">&quot;2022-12-31&quot;</span>)</span>
<span id="cb15-4"><a href="intro.html#cb15-4" tabindex="-1"></a>Fechas <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> start_year, <span class="at">to =</span> end_year, <span class="at">by =</span> <span class="st">&quot;quarter&quot;</span>)<span class="co">#Esta funcion crea un vector de fechas trimestrales, encontrado por investigacion</span></span>
<span id="cb15-5"><a href="intro.html#cb15-5" tabindex="-1"></a></span>
<span id="cb15-6"><a href="intro.html#cb15-6" tabindex="-1"></a><span class="co">#Se crea una serie de tiempo vacia que tiene como frecuencias las fechas trimestrales que creamos</span></span>
<span id="cb15-7"><a href="intro.html#cb15-7" tabindex="-1"></a>COL_zoo_trimestral <span class="ot">&lt;-</span> <span class="fu">zoo</span>(<span class="cn">NA</span>, <span class="at">order.by =</span> Fechas)</span>
<span id="cb15-8"><a href="intro.html#cb15-8" tabindex="-1"></a></span>
<span id="cb15-9"><a href="intro.html#cb15-9" tabindex="-1"></a><span class="co">#Se va llenando la nueva serie con los datos ANUALES de nuestra serie original, pero los trimestres entre los años siguen vacios</span></span>
<span id="cb15-10"><a href="intro.html#cb15-10" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(años)) {</span>
<span id="cb15-11"><a href="intro.html#cb15-11" tabindex="-1"></a>  year_start <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">index</span>(COL_zoo_trimestral) <span class="sc">==</span> <span class="fu">as.Date</span>(<span class="fu">paste</span>(años[i], <span class="st">&quot;01-01&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>)))</span>
<span id="cb15-12"><a href="intro.html#cb15-12" tabindex="-1"></a>  COL_zoo_trimestral[year_start] <span class="ot">&lt;-</span> ST_COL[i]</span>
<span id="cb15-13"><a href="intro.html#cb15-13" tabindex="-1"></a>}</span>
<span id="cb15-14"><a href="intro.html#cb15-14" tabindex="-1"></a></span>
<span id="cb15-15"><a href="intro.html#cb15-15" tabindex="-1"></a><span class="co">#Finalmente se lleman los datos trimestreales con aproximaciones por interpolacion lineal usando los datos anuales</span></span>
<span id="cb15-16"><a href="intro.html#cb15-16" tabindex="-1"></a>COL_zoo_trimestral <span class="ot">&lt;-</span> <span class="fu">na.approx</span>(COL_zoo_trimestral)</span></code></pre></div>
<p>Para mayor comodidad en la visualizacion de graficas (ya que ahora si contamos con mas datos), usaremos la libreria dygraphs, una libreria de visualizacion de series de tiempo propuesta en el debate ‘Visualizacion de series de tiempo’</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="intro.html#cb16-1" tabindex="-1"></a><span class="fu">dygraph</span>(COL_zoo_trimestral) <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="intro.html#cb16-2" tabindex="-1"></a>  <span class="fu">dyRangeSelector</span>()  <span class="co"># Agrega un selector de rango para el zoom</span></span></code></pre></div>
<div class="dygraphs html-widget html-fill-item" id="htmlwidget-1d453cee934ab5568c38" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-1d453cee934ab5568c38">{"x":{"attrs":{"labels":["quarter","V1"],"legend":"auto","retainDateWindow":false,"axes":{"x":{"pixelsPerLabel":60}},"showRangeSelector":true,"rangeSelectorHeight":40,"rangeSelectorPlotFillColor":" #A7B1C4","rangeSelectorPlotStrokeColor":"#808FAB","interactionModel":"Dygraph.Interaction.defaultModel"},"scale":"quarterly","annotations":[],"shadings":[],"events":[],"format":"date","data":[["1990-01-01T00:00:00.000Z","1990-04-01T00:00:00.000Z","1990-07-01T00:00:00.000Z","1990-10-01T00:00:00.000Z","1991-01-01T00:00:00.000Z","1991-04-01T00:00:00.000Z","1991-07-01T00:00:00.000Z","1991-10-01T00:00:00.000Z","1992-01-01T00:00:00.000Z","1992-04-01T00:00:00.000Z","1992-07-01T00:00:00.000Z","1992-10-01T00:00:00.000Z","1993-01-01T00:00:00.000Z","1993-04-01T00:00:00.000Z","1993-07-01T00:00:00.000Z","1993-10-01T00:00:00.000Z","1994-01-01T00:00:00.000Z","1994-04-01T00:00:00.000Z","1994-07-01T00:00:00.000Z","1994-10-01T00:00:00.000Z","1995-01-01T00:00:00.000Z","1995-04-01T00:00:00.000Z","1995-07-01T00:00:00.000Z","1995-10-01T00:00:00.000Z","1996-01-01T00:00:00.000Z","1996-04-01T00:00:00.000Z","1996-07-01T00:00:00.000Z","1996-10-01T00:00:00.000Z","1997-01-01T00:00:00.000Z","1997-04-01T00:00:00.000Z","1997-07-01T00:00:00.000Z","1997-10-01T00:00:00.000Z","1998-01-01T00:00:00.000Z","1998-04-01T00:00:00.000Z","1998-07-01T00:00:00.000Z","1998-10-01T00:00:00.000Z","1999-01-01T00:00:00.000Z","1999-04-01T00:00:00.000Z","1999-07-01T00:00:00.000Z","1999-10-01T00:00:00.000Z","2000-01-01T00:00:00.000Z","2000-04-01T00:00:00.000Z","2000-07-01T00:00:00.000Z","2000-10-01T00:00:00.000Z","2001-01-01T00:00:00.000Z","2001-04-01T00:00:00.000Z","2001-07-01T00:00:00.000Z","2001-10-01T00:00:00.000Z","2002-01-01T00:00:00.000Z","2002-04-01T00:00:00.000Z","2002-07-01T00:00:00.000Z","2002-10-01T00:00:00.000Z","2003-01-01T00:00:00.000Z","2003-04-01T00:00:00.000Z","2003-07-01T00:00:00.000Z","2003-10-01T00:00:00.000Z","2004-01-01T00:00:00.000Z","2004-04-01T00:00:00.000Z","2004-07-01T00:00:00.000Z","2004-10-01T00:00:00.000Z","2005-01-01T00:00:00.000Z","2005-04-01T00:00:00.000Z","2005-07-01T00:00:00.000Z","2005-10-01T00:00:00.000Z","2006-01-01T00:00:00.000Z","2006-04-01T00:00:00.000Z","2006-07-01T00:00:00.000Z","2006-10-01T00:00:00.000Z","2007-01-01T00:00:00.000Z","2007-04-01T00:00:00.000Z","2007-07-01T00:00:00.000Z","2007-10-01T00:00:00.000Z","2008-01-01T00:00:00.000Z","2008-04-01T00:00:00.000Z","2008-07-01T00:00:00.000Z","2008-10-01T00:00:00.000Z","2009-01-01T00:00:00.000Z","2009-04-01T00:00:00.000Z","2009-07-01T00:00:00.000Z","2009-10-01T00:00:00.000Z","2010-01-01T00:00:00.000Z","2010-04-01T00:00:00.000Z","2010-07-01T00:00:00.000Z","2010-10-01T00:00:00.000Z","2011-01-01T00:00:00.000Z","2011-04-01T00:00:00.000Z","2011-07-01T00:00:00.000Z","2011-10-01T00:00:00.000Z","2012-01-01T00:00:00.000Z","2012-04-01T00:00:00.000Z","2012-07-01T00:00:00.000Z","2012-10-01T00:00:00.000Z","2013-01-01T00:00:00.000Z","2013-04-01T00:00:00.000Z","2013-07-01T00:00:00.000Z","2013-10-01T00:00:00.000Z","2014-01-01T00:00:00.000Z","2014-04-01T00:00:00.000Z","2014-07-01T00:00:00.000Z","2014-10-01T00:00:00.000Z","2015-01-01T00:00:00.000Z","2015-04-01T00:00:00.000Z","2015-07-01T00:00:00.000Z","2015-10-01T00:00:00.000Z","2016-01-01T00:00:00.000Z","2016-04-01T00:00:00.000Z","2016-07-01T00:00:00.000Z","2016-10-01T00:00:00.000Z","2017-01-01T00:00:00.000Z","2017-04-01T00:00:00.000Z","2017-07-01T00:00:00.000Z","2017-10-01T00:00:00.000Z","2018-01-01T00:00:00.000Z","2018-04-01T00:00:00.000Z","2018-07-01T00:00:00.000Z","2018-10-01T00:00:00.000Z","2019-01-01T00:00:00.000Z","2019-04-01T00:00:00.000Z","2019-07-01T00:00:00.000Z","2019-10-01T00:00:00.000Z","2020-01-01T00:00:00.000Z","2020-04-01T00:00:00.000Z","2020-07-01T00:00:00.000Z","2020-10-01T00:00:00.000Z","2021-01-01T00:00:00.000Z","2021-04-01T00:00:00.000Z","2021-07-01T00:00:00.000Z","2021-10-01T00:00:00.000Z","2022-01-01T00:00:00.000Z"],[8434.959000000001,8433.791219178083,8432.6104630137,8431.41673150685,8430.223,8471.837273972602,8513.913928767124,8556.452964383561,8598.992,8670.149773224044,8741.307546448088,8813.247273224044,8885.187,8967.867410958905,9051.466493150685,9135.984246575343,9220.502,9293.921780821918,9368.157336986302,9443.208668493151,9518.26,9523.194465753426,9528.18375890411,9533.227879452055,9538.272000000001,9576.252316939892,9614.232633879781,9652.630316939891,9691.028,9663.319835616439,9635.303802739727,9606.979901369863,9578.656000000001,9441.798054794521,9303.419465753424,9163.520232876712,9023.620999999999,9051.902698630136,9080.498638356165,9109.408819178081,9138.319,9140.329453551913,9142.339907103826,9144.372453551912,9146.405000000001,9167.665219178083,9189.1616630137,9210.89433150685,9232.627,9287.046424657534,9342.070509589041,9397.699254794521,9453.328,9542.822273972602,9633.310928767123,9724.793964383562,9816.277,9899.42787704918,9982.57875409836,10066.64337704918,10150.708,10284.35676712329,10419.49052054794,10556.10926027397,10692.728,10835.70471232877,10980.27005479452,11126.42402739726,11272.578,11330.5101369863,11389.08596438356,11448.30548219178,11507.525,11507.57273770492,11507.62047540984,11507.66873770492,11507.717,11602.02861643836,11697.38813972603,11793.79556986301,11890.203,12059.8007260274,12231.28287123288,12404.64943561644,12578.016,12666.03106849315,12755.02408219178,12844.99504109589,12934.966,13066.76905737705,13198.5721147541,13331.82355737705,13465.075,13581.74360273973,13699.70852328767,13818.96976164384,13938.231,14006.64505479452,14075.81926575342,14145.75363287671,14215.688,14250.82005479452,14286.34246575343,14322.25523287671,14358.168,14352.38651639344,14346.60503278689,14340.76001639344,14334.915,14357.48157534247,14380.29889041096,14403.36694520548,14426.435,14473.21034246575,14520.5054109589,14568.32020547945,14616.135,14305.9834109589,13992.38569315069,13675.34184657534,13358.298,13682.24681147541,14006.19562295082,14333.70431147541,14661.213,14896.82535616438,15135.05562739726,15375.90381369863,15616.752]]},"evals":["attrs.interactionModel"],"jsHooks":[]}</script>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="intro.html#cb17-1" tabindex="-1"></a><span class="fu">summary</span>(COL_zoo_trimestral)</span></code></pre></div>
<pre><code>##      Index            COL_zoo_trimestral
##  Min.   :1990-01-01   Min.   : 8430     
##  1st Qu.:1998-01-01   1st Qu.: 9294     
##  Median :2006-01-01   Median :10693     
##  Mean   :2005-12-31   Mean   :11293     
##  3rd Qu.:2014-01-01   3rd Qu.:13682     
##  Max.   :2022-01-01   Max.   :15617</code></pre>
<p>Sin embargo nuevamente recordemos que trabajamos con datos aproximados asi que aunque las graficas se parezcan, aun habra ligeras diferencias comparadas con la realidad.</p>
<p>Volvemos a convertir los datos a una serie de tiempo de tipo ts</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="intro.html#cb19-1" tabindex="-1"></a>ST_TRIMESTRAL <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">coredata</span>(COL_zoo_trimestral), <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1990</span>, <span class="dv">1</span>), <span class="at">frequency =</span> <span class="dv">4</span>)</span></code></pre></div>
<p>Luego descomponemos la serie, analicemos su tendencia</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="intro.html#cb20-1" tabindex="-1"></a>COL_DECOMP <span class="ot">&lt;-</span> <span class="fu">decompose</span>(ST_TRIMESTRAL) <span class="co">#Descompone la serie en tendencia, estacionalidad y ruido</span></span>
<span id="cb20-2"><a href="intro.html#cb20-2" tabindex="-1"></a><span class="fu">plot</span>(COL_DECOMP<span class="sc">$</span>trend, <span class="at">main =</span> <span class="st">&quot;Tendencia&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Valores&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Aqui la serie es mayormente creciente(salvo por algunas fluctuaciones en secciones especificas) lo que evidencia una tendencia positiva SALVO en una caida abrupta y significativa, producto de un evento particular que afecto profundamente el comportamiento constante de los datos (Dicho evento claramente es la pandemia)</p>
<p>Ajustemos la serie ahora por desestacionalidad para eliminar todo rastro de estacionalidad que la serie posee (ya que no es significativo trabajar con ella)</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="intro.html#cb21-1" tabindex="-1"></a>EST_COL <span class="ot">&lt;-</span> <span class="fu">seasadj</span>(COL_DECOMP) <span class="co"># Elimina el componente estacional de la serie, devolviendola sin estos efectos</span></span>
<span id="cb21-2"><a href="intro.html#cb21-2" tabindex="-1"></a><span class="fu">plot</span>(ST_TRIMESTRAL,<span class="at">main =</span><span class="st">&quot;GPD Per Capita ORIGINAL VS DESESTACIONALIZADO&quot;</span>)</span>
<span id="cb21-3"><a href="intro.html#cb21-3" tabindex="-1"></a><span class="fu">lines</span>(EST_COL, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span>
<span id="cb21-4"><a href="intro.html#cb21-4" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;Serie original&quot;</span>, <span class="st">&quot;Serie desestacionalizada&quot;</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="at">lty =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Luego podemos ver que el grafico desestacionalizado es exactamente igual al grafico original (salvo por unas minusculas diferencias que destacan a simple vista ), esto es obvio ya que en el analisis al grafico de rezagos, concluimos que la estacionalidad presente en nuestros datos era tan debil que no haria diferencia alguna si la eliminamos.</p>
<p>Con esto ultimo listo ya es hora de poder proponer distintos modelos que nos ayuden a explicar el comportamiento de nuestra serie de tiempo esperando en lo mejor posible, encontrar el que mejor se ajuste a los datos y al que podamos aplicarle analisis de prediccion</p>
<p>NOTA: NO se planea hacer predicciones usando los modelos propuestos aun hasta que llegue la hora de compararlos entre si y evaluar el alcance y precision de su prediccion frente a otros.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelo-de-regresion-lineal.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/01-intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
